### ISSUE TITLE
Is there anyway to invoke arbitary external `cargo` cmd, such as the `cargo-auditable` with `cargo-zigbuild`?

### ISSUE THREAD

**Issue by NobodyXu** [rust-cross/cargo-zigbuild#105]
In cargo-quickinstall, we use `cargo-auditable` to build the crates to embed dependencies versions into the final binary so that it is auditable by crates like `cargo-audit`.

Currently, we creates a file called `zig.sh` which then calls `cargo-zigbuild zig cc --` and specify it as the `CC` and `-C linker`
https://github.com/cargo-bins/cargo-quickinstall/pull/180 .

It would be great if we can directly call cargo-zigbuild with cargo-auditable, e.g. `cargo-zigbuild auditable ...`

**Comment by messense** [comment]
I thought it should be `cargo auditable zigbuild`?

**Comment by NobodyXu** [comment]
> I thought it should be `cargo auditable zigbuild`?

We need to install the crates to CARGO_ROOT, zigbuild would only build the crate.

**Comment by messense** [comment]
I don't know if it works now, but if `cargo-auditable` supports setting the `CARGO` env var, this might just work?

```bash
CARGO=cargo-zigbuild cargo auditable install
```

**Comment by NobodyXu** [comment]
I think CARGO will be set by cargo when calling subcommands, so I don't think this would work as it would be overwritten by cargo.

And I think cargo doesn't have a CARGO_WRAPPER argument.

I think cargo-zigbuild could just export a few environment variables (CC, RUSTC_FLAGS) to call  wrapper of cargo-zigbuild?

**Comment by messense** [comment]
What about `CARGO=cargo-zigbuild cargo-auditable auditable install`? it should bypass `cargo`.

> And I think cargo doesn't have a CARGO_WRAPPER argument.

Yeah, it's just an idea that `cargo-auditable` could support.



> I think cargo-zigbuild could just export a few environment variables (CC, RUSTC_FLAGS) to call wrapper of cargo-zigbuild?

I'm not totally sure what you mean by this, but pull requests are welcome!

**Comment by NobodyXu** [comment]
I will have a try of setting cargo-zigbuild later and let you know the result

**Comment by NobodyXu** [comment]
> Looks like it works.

Thanks!

I've tried it on my laptop and it indeed works!
