### ISSUE TITLE
Missing symbol `__powidf2` in armv7 gnu/musl

### ISSUE THREAD

**Issue by NobodyXu** [rust-cross/cargo-zigbuild#107]
[cocogitto v5.3.1 armv7-unknown-linux-gnueabihf
](https://github.com/cargo-bins/cargo-quickinstall/actions/runs/4369443196/jobs/7643240024)
[grcov 0.8.13 armv7-unknown-linux-musleabihf
](https://github.com/cargo-bins/cargo-quickinstall/actions/runs/4369061137/jobs/7642418748)

**Comment by NobodyXu** [comment]
Thanks!
I will close this since this is an upstream issue.

@messense I think you could put this in `README.md#Caveats` so that people won't have to ask this again.

**Comment by messense** [comment]
> I think you could put this in `README.md#Caveats`

Done.
