### ISSUE TITLE
Atomics are not linked into the binary

### ISSUE THREAD

**Issue by link2xt** [rust-cross/cargo-zigbuild#109]
I have a minimal example at https://github.com/link2xt/openssl-cross-example
It is a binary which links against OpenSSL via `openssl-sys` which in turn depends on the C code of OpenSSL provided in `openssl-src` crate.

There is a build script `scripts/build.sh` in the repository which calls `cargo-build`.

The build fails with errors like this:
```
          ld.lld: error: undefined symbol: __atomic_load
          >>> referenced by bio_lib.c:689 (crypto/bio/bio_lib.c:689)
          >>>               bio_lib.o:(BIO_free_all) in archive ...
```
even though Zig should provide [`__atomic_load`](https://github.com/ziglang/zig/blob/4ea2f441df36cec61e1017f4d795d4037326c98c/lib/compiler_rt/atomics.zig#L120-L125).

**Comment by messense** [comment]
Probably due to https://github.com/ziglang/zig/issues/4911 which is a known upstream issue.
