### ISSUE TITLE
Use `x86` instead of `i386` when compiling for i586- and i686- Rust targets on Linux

### ISSUE THREAD

**Issue by link2xt** [rust-cross/cargo-zigbuild#120]
New Zig versions use `x86` instead of `i386` as an architecture name: https://github.com/ziglang/zig/pull/13101

For Windows there is already a check for new Zig:
https://github.com/rust-cross/cargo-zigbuild/blob/f2c70a102908aabfe7256fad3533a3701839acbe/src/zig.rs#L735-L738
It was introduced in https://github.com/rust-cross/cargo-zigbuild/pull/110

For Linux cargo-zigbuild still uses "i386" unconditionally:
https://github.com/rust-cross/cargo-zigbuild/blob/f2c70a102908aabfe7256fad3533a3701839acbe/src/zig.rs#L713-L714

I am filing the issue so it is easier to find the reason for those who try to compile for i686 on Linux using nightly Zig builds. There is however no need to fix this now as I plan to switch from cargo-zigbuild to my own simple wrapper here: https://github.com/deltachat/deltachat-core-rust/pull/4243 Maybe it is easier to wait until Zig 0.11 release and switch to using `x86` unconditionally or at least wait for someone requesting this bug to be fixed in the comment to this issue.

**Comment by messense** [comment]
That change was reverted in https://github.com/ziglang/zig/pull/13460?
