### ISSUE TITLE
be more specific on missing compiler_rt functions/compiler_rt support status

### ISSUE THREAD

**Issue by matu3ba** [rust-cross/cargo-zigbuild#122]
Would be nice to mention which ones are supported can be derived from https://github.com/ziglang/zig/blob/master/lib/compiler_rt/README.md

More concrete, from the libgcc runtime functions ([Integer library routines](https://gcc.gnu.org/onlinedocs/gccint/Integer-library-routines.html#Integer-library-routines) and [Soft float library routines](https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html#Soft-float-library-routines) all except addv, subv, mulv are supported.
See in the table __addvsi3 and the followup symbols.

Reason being is that the build system changes alot, so I haven't integrated the panic testrunner yet https://github.com/ziglang/zig/pull/14351 (besides other shennanigans I'd like to cleanup first like os.zig still containing the non-portable posix stuff).

The following deviating compiler_rt symbols are (partially) supported: ARM , PPC and SPARC but support is incomplete. For example, there is https://github.com/ziglang/zig/issues/14634 for ARM (albeit my list is not complete).

That way, if somebody has a use case, they can just drop by and implement the missing ones.

**Comment by messense** [comment]
Added a link to https://github.com/ziglang/zig/blob/master/lib/compiler_rt/README.md in https://github.com/rust-cross/cargo-zigbuild/commit/ad81ecaeebf28b64f41256a0912713d2b789f3d3.
