### ISSUE TITLE
failed to run custom build command for openssl-sys v0.9.82

### ISSUE THREAD

**Issue by 525bigword** [rust-cross/cargo-zigbuild#123]
I compile raspberry pie on windows10
i using cargo zigbuild --target armv7-unknown-linux-musleabihf still reports an error:
failed to run custom build command for openssl-sys v0.9.82
failed to run custom build command for zstd-sys v2.0.7+zstd.1.5.4
But I will not achieve similar problems by running directly or cargo build --release

**Comment by messense** [comment]
You need to compile `openssl` from source, you can do that by using the [`vendored`](https://docs.rs/openssl/latest/openssl/#vendored) feature. Same for `zstd`, look it up in its documentation.
