### ISSUE TITLE
Cross compiling and linking OpenSSL?

### ISSUE THREAD

**Issue by VorpalBlade** [rust-cross/cargo-zigbuild#127]
I have been using cross before, but was interested in zigbuild because it supposedly offers better build speeds.

However, it isn't clear to me how to deal with openssl-sys. For cross (which uses docker/podman containers) you can use a pre build step to install the openssl system package to link against: https://github.com/cross-rs/cross/wiki/Recipes#pre-build

How would this work with zigbuild?

**Comment by messense** [comment]
You can static compile openssl.

See https://docs.rs/openssl/latest/openssl/#vendored

**Comment by VorpalBlade** [comment]
That is rather slower than installing it as a binary as a pre-build step. Besides, I want to dynamically link OpenSSL and use the system provided library rather than link it statically into my binary.

So... No that is not a solution.

**Comment by NobodyXu** [comment]
> That is rather slower than installing it as a binary as a pre-build step. Besides, I want to dynamically link OpenSSL and use the system provided library rather than link it statically into my binary.
> 
> 
> 
> So... No that is not a solution.

@VorpalBlade You can override environment variable PKG_CONFIG_PATH to provide your own pkg-config data, pointing to your openssl installation.
