### ISSUE TITLE
support Virtual workspace

### ISSUE THREAD

**Issue by tingfeng-key** [rust-cross/cargo-zigbuild#128]
tip:
`Should have a root package`

**Comment by messense** [comment]
Please be more specific.

**Comment by tingfeng-key** [comment]
When I run a command in a virtual workspace:
`cargo zigbuild -p admin --target universal2-apple-darwin`
the prompt is:
`Should have a root packag`

![image](https://user-images.githubusercontent.com/13976521/233248284-c1b83c84-f75d-466e-a0ae-6fbe52debdcb.png)

https://github.com/oli-obk/cargo_metadata/blob/184e836e3e197a07f5ea7eb30b5662163f0bc4ea/src/lib.rs#L180

`cargo metadata` result:
![image](https://user-images.githubusercontent.com/13976521/233248713-7f53d509-f0e2-410a-8c81-22ec6fe7d9b8.png)

**Comment by messense** [comment]
I don't need to use this feature personally, pull requests to fix this are welcome if you are up for it.

**Comment by messense** [comment]
Closing because you have removed important context.
