### ISSUE TITLE
Document use with bindgen

### ISSUE THREAD

**Issue by TheButlah** [rust-cross/cargo-zigbuild#144]
I have been trying to get this to work with bindgen for about two days, to no avail. It works with `cargo build` but not with `cargo zigbuild`. I suspect this is because `cargo zigbuild` enforces zig's sysroot, which seemingly lacks `stdio.h`?

Documenting which specific combination of `builder.clang_arg()` or environment variables should be provided would be really helpful:
* Do I pass `--target` as a clang arg to the bindgen builder?
* What about `--isysroot`?

Note: I am attempting to cross compile from a m2 mac to `aarch64-unknown-linux-gnu`

**Comment by TheButlah** [comment]
Possibly related, I could just be hitting bugs in zigbuild: #140

**Comment by TheButlah** [comment]
I would not say that this is documented yet

**Comment by messense** [comment]
Feel free to send PRs to document it.

**Comment by crutchcorn** [comment]
Opened a PR @messense: https://github.com/rust-cross/cargo-zigbuild/pull/403
