### ISSUE TITLE
not working on nix os

### ISSUE THREAD

**Issue by FU3X** [rust-cross/cargo-zigbuild#146]
[user@nixos:~/Documents/Source/hello-world]$ cargo zigbuild --target x86_64-pc-windows-gnu 
Error: failed to copy file from /nix/store/wsi9bc39az42zmclk7fchx8vwssivmp0-zig-0.10.1/lib/zig/libc/mingw/lib-common/api-ms-win-core-synch-l1-2-0.def to /nix/store/wsi9bc39az42zmclk7fchx8vwssivmp0-zig-0.10.1/lib/zig/libc/mingw/lib-common/synchronization.def

Caused by:
    Read-only file system (os error 30)

**Comment by messense** [comment]
I don't use NixOS so please feel free to send PRs to fix it if you want to use it.
