### ISSUE TITLE
Force a generic cpu build?

### ISSUE THREAD

**Issue by cgbur** [rust-cross/cargo-zigbuild#150]
I am using this in a build system and want to be sure that the x86 artifacts are as generic as possible to work on any cpu. Currently when I inspect the build log I see that cargo is using the following

```sh
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
```

and then in the `zig cc`...`.sh` execution I see

```sh
"-march=core2" "-msse" "-mfpmath=sse"
```

Is this the default and expected on every cpu at this point? Is there a way to specify that is should be more generic.

**Comment by messense** [comment]
You can probably tweak `RUSTFLAGS`/`CFLAGS` and etc to achieve that and I think you need to build your own `libstd` too since the default one was compiled with sse enabled.
