### ISSUE TITLE
unsupported linker arg: -exported_symbols_list

### ISSUE THREAD

**Issue by sigmaSd** [rust-cross/cargo-zigbuild#164]
error: unsupported linker arg: -exported_symbols_list

I understand that zig 0.11.0 errors on unrecognized flags, should unknown flags be hardcoded ? if that's the case I can add it to zig.rs

**Comment by messense** [comment]
Feel free to send a PR.

**Comment by messense** [comment]
Partially fixed by #171, `-Wl,-exported_symbols_list,<path>` is handled but `-Wl,-exported_symbols_list <path>` isn't handled yet.
