### ISSUE TITLE
unsupported linker arg: -dylib

### ISSUE THREAD

**Issue by serjflint** [rust-cross/cargo-zigbuild#177]
I am cross-compiling Ruff from Ubuntu to MacOS and got another error when compiling [pep440_rs](https://github.com/konstin/pep440-rs):
`..."-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs" "-undefined" "dynamic_lookup"...`

**Comment by messense** [comment]
See also https://github.com/ziglang/zig/issues/14757

**Comment by serjflint** [comment]
Thank you. Now it compiles.
