### ISSUE TITLE
How to build with `cargo auditable`

### ISSUE THREAD

**Issue by NuSkooler** [rust-cross/cargo-zigbuild#192]
Hi, thanks for the great project!

We would like our builds to contain [auditable](https://github.com/rust-secure-code/cargo-auditable) information. Normally this would be done via `cargo auditable --release` for example. Is there a way to utilize cargo-zigbuild and auditable together?

**Comment by NobodyXu** [comment]
`export CARGO=cargo-zigbuild cargo auditable`, that's how cargo-binstall does it

**Comment by NuSkooler** [comment]
@NobodyXu Thanks for the information and quick reply! Perhaps I'm doing something wrong, but I tried this without luck:

```bash
export CARGO="cargo-zigbuild cargo-auditable"
cargo-auditable auditable build --release --target x86_64-pc-windows-gnu
```

But that yields
```
error: linker `x86_64-w64-mingw32-gcc` not found
```

Any ideas?

**Comment by NobodyXu** [comment]
Please try this:

```
export CARGO="cargo-zigbuild"
cargo-auditable auditable build --release --target x86_64-pc-windows-gnu
```

**Comment by NuSkooler** [comment]
@NobodyXu Thank you so much, that works (and makes sense)!
