### ISSUE TITLE
Command::new("cargo-zigbuild") doesn't shutdown when aborting

### ISSUE THREAD

**Issue by cybersoulK** [rust-cross/cargo-zigbuild#194]
```rust
let mut process = tokio::process::Command::new("cargo-zigbuild")
                .args(["zigbuild", "--bin", &bin, "--target", &target, release])
                .spawn().unwrap();
                
                
 tokio::time::sleep(Duration::from_secs(4)).await;
let res = process.kill().await; 
println!("{res:?}");
               
process.wait().await.unwrap();
```

It prints Ok(()) to console, but continues running. 

tried the following as well: (both std::process and tokio::process have the same issue) 
```rust
Command::new("cargo-zigbuild").arg("build") 
and
 Command::new("cargo").arg("zigbuild")
 ```
 
 The following works:
 ```rust
 Command::new("cargo").arg("build") 
 ```
 
 I asked the rust community, they think this behaviour is weird. This is what they suggested the issue was:
>  Perhaps they forgot to install this signal handler.

I need the correct behaviour for automating my builds, and allow it to abort on an external signal. thank you!

**Comment by cybersoulK** [comment]
oh, my compilation is mac ventura 13.4 if that's useful.

**Comment by messense** [comment]
You are welcome to investigate and send PRs to fix it.

**Comment by konnorandrews** [comment]
For anyone else that encounters this you can use https://docs.rs/command-group/latest/command_group/index.html to spawn cargo-zigbuild in a process group which then can be killed. This is what a terminal does (and why ctrl-c works as expected). It may still be a good idea to add a ctrl-c handler the cargo-zigbuild to make this usecase easier.

For those that don't want to use command_group you can use the following.
```rs
// Set the process group to the child's process ID (works only on unix systems)
command.process_group(0);

...

// Perform the kill by sending a signal to the *process group* instead of just the one process.
signal::killpg(Pid::from_raw(child.id() as _), Signal::SIGINT).unwrap(); // note the signal used here can be changed if needed.

// continue with child cleanup like .wait()
```

**Comment by cybersoulK** [comment]
This worked! Thank you so much!

I forked zigbuild and i tried for several hours, but i don't have enough experience to make this feature work from the inside.
