### ISSUE TITLE
Is cross-compilation on Linux for Windows possible?

### ISSUE THREAD

**Issue by lnicola** [rust-cross/cargo-zigbuild#200]
With `x86_64-pc-windows-gnu` I get:

```
  = note: lld-link: warning: ignoring unknown argument: -exclude-symbols:_ZN3std2rt10lang_start17h939a6fb8a2a68f4dE
          lld-link: error: -exclude-symbols:_ZN3std2rt10lang_start17h939a6fb8a2a68f4dE is not allowed in .drectve
```

while `x86_64-pc-windows-msvc` (understandably?) fails on my system with `note: error: FileNotFound`.

**Comment by messense** [comment]
We have partial support for Windows gnu, the `lld-link` error message suggests that you might have misconfigured the target because `lld-link` is for `msvc`.

For windows msvc, use [cargo-xwin](https://github.com/rust-cross/cargo-xwin).

**Comment by lnicola** [comment]
> suggests that you might have misconfigured the target because lld-link is for msvc.

I didn't configure anything :sweat_smile:.

> For windows msvc, use [cargo-xwin](https://github.com/rust-cross/cargo-xwin).

Thank you, that works. I'll close the issue, then. Whoever needs Windows support can find it.
