### ISSUE TITLE
unable to find dynamic system library 'atomic'

### ISSUE THREAD

**Issue by xutianyi1999** [rust-cross/cargo-zigbuild#252]
OS: Ubuntu 22.04
Rust: nightly-x86_64-unknown-linux-gnu
cargo-zigbuild-0.18.4 
ziglang-0.12.0

Build command: cargo zigbuild --release --target armv7-unknown-linux-gnueabihf

Error message
```
 error: unable to find dynamic system library 'atomic' using strategy 'no_fallback'. searched paths:
            /home/runner/work/fubuki-test/fubuki-test/target/armv7-unknown-linux-gnueabihf/release/deps/libatomic.so
            /home/runner/work/fubuki-test/fubuki-test/target/release/deps/libatomic.so
            /home/runner/work/fubuki-test/fubuki-test/target/armv7-unknown-linux-gnueabihf/release/build/libmimalloc-sys-ca91151723eed5d5/out/libatomic.so
            /home/runner/work/fubuki-test/fubuki-test/target/armv7-unknown-linux-gnueabihf/release/build/netstack-lwip-e8f8aeaad777c356/out/libatomic.so
            /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libatomic.so
            /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/libatomic.so
```
[All build message](https://github.com/xutianyi1999/fubuki-test/actions/runs/9170811863/job/25213797163)

libatomic link instruction
```rust
println!("cargo:rustc-link-lib=dylib=atomic");
```

**Comment by messense** [comment]
Nothing we can do here, zig has some known issue for atomic, for example https://github.com/ziglang/zig/issues/14889.

**Comment by messense** [comment]
FYI, your best chance of getting this fixed is fixing https://github.com/microsoft/mimalloc/issues/634.

**Comment by messense** [comment]
scrtach that, it should be fixed in https://github.com/purpleprotocol/mimalloc_rust/blob/a9c410c248859d3f55fbb7d29a88f28cdf296f6b/libmimalloc-sys/build.rs#L58-L61 because armv7 and later does not require libatomic.
