### ISSUE TITLE
cargo-zigbuild 0.19.0 test failure

### ISSUE THREAD

**Issue by chenrui333** [rust-cross/cargo-zigbuild#257]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
            error: unknown CPU: 'westmere'
            
  
  error: could not compile `hello_world` (bin "hello_world") due to 1 previous error
```

</details>

relates to Homebrew/homebrew-core#175201

**Comment by messense** [comment]
Is there any `RUSTFLAGS` set in homebrew? Cross compiling to aarch64-unknown-linux-gnu seems to pass here: https://github.com/rust-cross/cargo-zigbuild/actions/runs/9596022414/job/26461974137#step:19:24

**Comment by chenrui333** [comment]
could it be rust version issue?

**Comment by chenrui333** [comment]
I dont think we have `RUSTFLAGS` for test-bot setup.

**Comment by messense** [comment]
Well, Rust 1.79.0 also passes in https://github.com/rust-cross/cargo-zigbuild/actions/runs/9596022414/job/26461974137#step:4:80

**Comment by chenrui333** [comment]
Looks like deleting RUSTFLAGS fixed the issue, close via https://github.com/Homebrew/homebrew-core/pull/175201
