### ISSUE TITLE
Add --version

### ISSUE THREAD

**Issue by jayvdb** [rust-cross/cargo-zigbuild#272]
Most commands provide a `--version`.
Any chance `cargo-zigbuild` would be interested in doing that?

**Comment by messense** [comment]
Already supported.

```bash
$ cargo-zigbuild --version
cargo-zigbuild 0.19.1
```

**Comment by jayvdb** [comment]
Ah, it is `cargo zigbuild --version` which doesnt work, but `cargo-zigbuild --version` is good enough for me.

**Comment by messense** [comment]
It's just how `cargo` external subcommand works, `cargo zigbuild` is actually calling `cargo-zigbuild zigbuild`, adding a `--version` to that command doesn't feel right, like you won't expect a `--version` option in `cargo build` command.
