### ISSUE TITLE
Pass linker arguments on Windows with a linker @-file

### ISSUE THREAD

**Issue by calavera** [rust-cross/cargo-zigbuild#46]
When attempting to spawn the linker, Rust might go over the size limits for spawning new processes because of the large amount of information passed in the arguments list. To prevent this from happening, specially on windows where the limit is 32K, [Rust will put the linker arguments in an @-file](https://github.com/rust-lang/rust/blob/1dcff2d5077244f49687ea25070958f23bd9edc6/compiler/rustc_codegen_ssa/src/back/link.rs#L1345).

There are cases where Rust won't put the arguments in an @-file, but cargo-zigbuild will still fail because of going over this limit. This is caused because Zig adds additional arguments to the linker execution, which makes the execution fail.

I'd like to propose to change how the linker is spawned on Windows to capture the list of arguments and always pass them in an @-file. This way, it's be easier to prevent this problem.

The implementation could be the same that Rust uses, but implemented before calling `zig cc`: https://github.com/rust-lang/rust/blob/1dcff2d5077244f49687ea25070958f23bd9edc6/compiler/rustc_codegen_ssa/src/back/link.rs#L1345

You can see those failures following these links:

https://github.com/cargo-lambda/cargo-lambda/issues/77
https://ci.appveyor.com/project/AWSSAMCLI/aws-lambda-builders/builds/44107059

**Comment by messense** [comment]
Unfortunately we will need to want for a fix for https://github.com/ziglang/zig/issues/10881

**Comment by Gankra** [comment]
Updating this with context/keywords (NameTooLong) for people hitting this in 2023. The issue now looks like:

```
   Compiling reqwest v0.11.18                                                                                                                                             
   Compiling axoasset v0.5.0
   Compiling cargo-dist v0.1.0 (C:\Users\ninte\dev\cargo-dist\cargo-dist)
error: linking with `C:\Users\ninte\AppData\Local\cargo-zigbuild\0.17.0\zigcc-aarch64-unknown-linux-gnu.bat` failed: exit code: 1
  |
  = note: "cmd" "/c" "C:\\Users\\ninte\\AppData\\Local\\cargo-zigbuild\\0.17.0\\zigcc-aarch64-unknown-linux-gnu.bat" "C:\\Users\\ninte\\AppData\\Local\\Temp\\rustcFXcXzF\
  ****** A MILLION ARGUMENTS OMITTED FOR BREVITY ******
  = note: error(link): unable to spawn C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.10.1\zig.exe: NameTooLong
          error: UnableToSpawnSelf

          C:\Users\ninte\dev\cargo-dist>C:\Users\ninte\.cargo\bin\cargo-zigbuild.exe zig cc -- -target aarch64-linux-gnu  -g -Wl,--version-script=C:\Users\ninte\AppData\Local\cargo-zigbuild\0.17.0\fcntl.map -include C:\Users\ninte\AppData\Local\cargo-zigbuild\0.17.0\fcntl.h @C:\Users\ninte\AppData\Local\Temp\rustcFXcXzF\linker-arguments  


error: could not compile `cargo-dist` (bin "cargo-dist") due to previous error
```

I think you can *potentially* partially mitigate this by setting `codegen-units=1` in your build profile, as it can reduce the number of things that need to be linked (at the cost of slower builds). 

Unfortunately this workaround doesn't help the [hefty 356-package cargo-dist](https://github.com/axodotdev/cargo-dist/), as it still fails to build (without cgu=1 the invocation is over 180k chars and exceeds my terminal's backscroll, with cgu=1 it's "merely" 47k chars).

On the same machine, the [slimmer example application of axolotlsay](https://github.com/axodotdev/axolotlsay) builds fine.

For context I'm running:

> Microsoft Windows 11 Home 10.0.22621 Build 22621
> powershell 5.1.22621.1778 (BuildVersion 10.0.22621.1778)
> cargo 1.71.1 (7f1d04c00 2023-07-29)
> cargo-zigbuild 0.17.0
> zig 0.10.1
