### ISSUE TITLE
`cargo ziginstall`

### ISSUE THREAD

**Issue by Milo123459** [rust-cross/cargo-zigbuild#81]
`cargo install` but using zig as a linker

**Comment by messense** [comment]
While this seems useful, you usually install binary crates in host machine which `cargo install` should just work.

**Comment by NobodyXu** [comment]
The use case here is for [`cargo-quickinstall`](https://github.com/cargo-bins/cargo-quickinstall) where we build popular crates on GHA and provides pre-built binaries to the users.

**Comment by messense** [comment]
@NobodyXu Could you elaborate more on `cargo-quickinstall`'s use case? Doesn't `cargo zigbuild` already works for building crates?

**Comment by NobodyXu** [comment]
`cargo-quickinstall` use `cargo-install` to pull and build the latest version of popular crates.

**Comment by NobodyXu** [comment]
@messense We also use [`cargo-auditable`](https://github.com/rust-secure-code/cargo-auditable) to include the dependencies information in the crate so that tools like `cargo-audit` can scan for vulnerabilities.

**Comment by messense** [comment]
Added `cargo zigbuild install`(or `cargo-zigbuild install`) in #82.
